// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3uU7K4DiLjnb3aHJ2kS9ACJJKlABe3k',
    appId: '1:924152729551:web:5b017bdd93f08cffcf8cba',
    messagingSenderId: '924152729551',
    projectId: 'world-help-f6c7b',
    authDomain: 'world-help-f6c7b.firebaseapp.com',
    databaseURL: 'https://world-help-f6c7b-default-rtdb.firebaseio.com',
    storageBucket: 'world-help-f6c7b.appspot.com',
    measurementId: 'G-LXCC6DB1DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIvN2rOOPKW0ofrJZdGDsA-KcC5MakXk',
    appId: '1:924152729551:android:d6b4d55624256f09cf8cba',
    messagingSenderId: '924152729551',
    projectId: 'world-help-f6c7b',
    databaseURL: 'https://world-help-f6c7b-default-rtdb.firebaseio.com',
    storageBucket: 'world-help-f6c7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw5X1upgFCMte910ZCIzJyNg2eIe2lLr8',
    appId: '1:924152729551:ios:d7e295aa3a3532e5cf8cba',
    messagingSenderId: '924152729551',
    projectId: 'world-help-f6c7b',
    databaseURL: 'https://world-help-f6c7b-default-rtdb.firebaseio.com',
    storageBucket: 'world-help-f6c7b.appspot.com',
    iosClientId: '924152729551-c81cs2dmf55vl7gsbbiq4chs9d1up3v7.apps.googleusercontent.com',
    iosBundleId: 'com.world.help.worldhelps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw5X1upgFCMte910ZCIzJyNg2eIe2lLr8',
    appId: '1:924152729551:ios:6dc92db3902d42d4cf8cba',
    messagingSenderId: '924152729551',
    projectId: 'world-help-f6c7b',
    databaseURL: 'https://world-help-f6c7b-default-rtdb.firebaseio.com',
    storageBucket: 'world-help-f6c7b.appspot.com',
    iosClientId: '924152729551-43r8saidl42madg7plaagdj7g0cnbhuf.apps.googleusercontent.com',
    iosBundleId: 'com.world.help.worldhelps.RunnerTests',
  );
}
